version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/eventcatalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6815
      DatabaseServer: mssqlserver
      DatabaseName: CatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "6815:80"
    container_name: eventcatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://catalog
      CartUrl: http://cart
      IdentityUrl: http://10.0.6.153:6817
      CallBackUrl: http://localhost:6816
    ports:
      - "6816:80"
    container_name: webeventshop
    networks:
      - frontend
    depends_on:
      - catalog

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      MvcClient: http://localhost:6816
    ports:
      - "6817:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi
    environment:
      IdentityUrl: http://10.0.6.153:6818
      ConnectionString: basket.data
    ports:
      - "6818:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - tokenserver
      - basket.data

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1450:1433"
    container_name: eventsqlserver
    networks:
      - backend

  basket.data:
    image: redis
    container_name: basketdate
    ports:
      - "6081:6379"
    networks:
      - backend
